# Generated by Django 5.2.12 on 2026-03-07 10:08

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité (personnes)')),
                ('area_sqm', models.PositiveIntegerField(verbose_name='Surface (m²)')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tarif horaire (€)')),
                ('equipment', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, verbose_name='Équipements')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image_emoji', models.CharField(default='🏛️', max_length=10, verbose_name='Emoji')),
                ('color', models.CharField(default='#1a3a5a', max_length=7, verbose_name='Couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('requires_admin_only', models.BooleanField(default=False, verbose_name='Réservation admin uniquement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['name'],
            },
        ),
    ]
