# Generated by Django 5.2.17 on 2026-09-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_allowed_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='room',
            name='daily_rate_association',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tarif journalier — Associations (€)'),
        ),
        migrations.AddField(
            model_name='room',
            name='daily_rate_individual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tarif journalier — Particuliers (€)'),
        ),
    ]
