# Generated by Django 5.2.12 on 2026-03-07 10:08

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalService',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('icon', models.CharField(default='🏢', max_length=10, verbose_name='Emoji')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service municipal',
                'verbose_name_plural': 'Services municipaux',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Normale'), ('normal', 'Importante'), ('high', 'Urgente')], default='normal', max_length=10, verbose_name='Priorité')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('email_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'emails envoyés")),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
                ('services', models.ManyToManyField(to='notifications.municipalservice', verbose_name='Services destinataires')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
