# Generated by Django 5.2.12 on 2026-03-07 10:08

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('association', models.CharField(max_length=200, verbose_name='Association / Organisme')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Responsable')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_start', models.DateField(verbose_name='Date de début')),
                ('date_end', models.DateField(verbose_name='Date de fin')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('expected_attendees', models.PositiveIntegerField(default=0, verbose_name='Participants attendus')),
                ('description', models.TextField(verbose_name='Description')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Budget estimé (€)')),
                ('equipment_needs', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, verbose_name='Besoins logistiques')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=20, verbose_name='Statut')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Commentaire mairie')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_manifestations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Manifestation',
                'verbose_name_plural': 'Manifestations',
                'ordering': ['date_start'],
            },
        ),
    ]
