# Generated by Django 5.2.17 on 2026-09-10 16:51

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestations', '0004_equipment_quantities_and_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestationSettings',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='manifestations', editable=False, max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Décoché : la page Manifestation est masquée et la création de nouvelles demandes est bloquée. Les manifestations déjà approuvées restent visibles.', verbose_name='Manifestations activées')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres — Manifestations',
                'verbose_name_plural': 'Paramètres — Manifestations',
            },
        ),
    ]
