# Generated by Django 5.2.17 on 2026-09-10 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usergroup_customuser_reservation_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('association', 'Association')], default='particulier', max_length=20, verbose_name='Type de compte'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rna_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^W\\d{9}$', 'Le numéro RNA doit être au format W suivi de 9 chiffres (ex. W123456789).')], verbose_name='Numéro RNA'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='association',
            field=models.CharField(blank=True, max_length=200, verbose_name="Nom de l'association"),
        ),
    ]
