# Generated by Django 5.2.17 on 2026-09-10 17:28

from django.db import migrations

GROUP_NAMES = {"particulier": "Particulier", "association": "Association"}


def create_and_assign_groups(apps, schema_editor):
    """Crée les groupes "Particulier" et "Association", et y affecte chaque
    utilisateur existant selon son account_type actuel (déjà backfillé par
    la migration précédente à partir de l'ancien champ "association")."""
    UserGroup = apps.get_model("accounts", "UserGroup")
    CustomUser = apps.get_model("accounts", "CustomUser")

    groups = {
        account_type: UserGroup.objects.get_or_create(name=name)[0]
        for account_type, name in GROUP_NAMES.items()
    }

    for user in CustomUser.objects.all():
        group = groups.get(user.account_type)
        if group:
            user.reservation_groups.add(group)


def reverse_noop(apps, schema_editor):
    # Les groupes eux-mêmes ne sont pas supprimés au rollback : ils ont pu
    # être réutilisés depuis pour restreindre des salles (allowed_groups).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_account_type'),
    ]

    operations = [
        migrations.RunPython(create_and_assign_groups, reverse_noop),
    ]
